name: iaf2
channels:
  - conda-forge
  - bioconda
  - pytorch
dependencies:
  - cpuonly
  - conda-forge::python=3.11
  - conda-forge::pip
  - conda-forge::mkl==2024.2.0
  - conda-forge::dpcpp_linux-64==2024.2.0
  - conda-forge::dpcpp-cpp-rt==2024.2.0
  - conda-forge::mkl-devel==2024.2.0
  - conda-forge::openmm==8.0.0
  - conda-forge::pdbfixer==1.9
  - bioconda::hmmer=3.3.2
  - bioconda::hhsuite==3.3.0
  - bioconda::kalign2==2.04
  - pip:
    - onednn-cpu-iomp==2023.2.0
    - torch==2.1.0 
    - pybind11==2.11.1
    - absl-py==2.0.0
    - biopython==1.81
    - chex==0.1.84
    - dm-haiku==0.0.10
    - dm-tree==0.1.8
    - immutabledict==3.0.0
    - ml-collections==0.1.1
    - numpy==1.26.1
    - scipy==1.11.3
    - tensorflow==2.14.0
    - pandas==2.1.1
    - psutil==5.9.6
    - tqdm==4.65.0
    - joblib==1.3.2
    - pragzip==0.6.0
    - intel-extension-for-pytorch==2.1.0
    - jax==0.4.21
    - jaxlib==0.4.21

  - conda-forge::autoconf==2.71
  - conda-forge::make==4.3