name: iaf_new
channels:
  - pytorch
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - cpuonly
  - pip
  - openmm
  - kalign2
  - jemalloc
  - pdbfixer
  - pytorch==2.0.1
  - pip:
    - absl-py
    - biopython
    - chex
    - dm-haiku
    - dm-tree
    - immutabledict
    - intel-extension-for-pytorch==2.0.100
    - jax==0.4.8
    - jaxlib==0.4.7
    - joblib
    - ml-collections
    - numpy
    - pandas
    - psutil
    - pybind11
    - scipy
    - tensorflow-cpu
    - torch==2.0.1
    - tqdm
