name: iaf2
channels:
  - pytorch
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - pip
  - openmm
  - pdbfixer
  - kalign2
  - hmmer
  - jemalloc
  - pytorch
  - cpuonly
  - pip:
    - absl-py
    - biopython
    - chex
    - dm-haiku
    - dm-tree
    - immutabledict
    - intel-extension-for-pytorch
    - jax
    - jaxlib
    - joblib
    - ml-collections
    - numpy
    - pandas
    - psutil
    - scipy
    - tensorflow-cpu
    - tqdm
